In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz

--2025-01-22 13:21:14--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz
Resolving github.com (github.com)... 140.82.114.4
connected. to github.com (github.com)|140.82.114.4|:443...
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/ea580e9e-555c-4bd0-ae73-43051d8e7c0b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250122T122115Z&X-Amz-Expires=300&X-Amz-Signature=24d174cc8af03bac59e103c9928bb6f79676727becd077aaed90231a13267d4b&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2019-10.csv.gz&response-content-type=application%2Foctet-stream [following]
--2025-01-22 13:21:15--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/ea580e9e-555c-4bd0-ae73-43051d8e7c0b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250122T122115Z&X-Amz-Expires=300&X-Amz-Signature=24d174cc8af03bac59e103c9928bb6f79676727becd077aaed90231a13267d4b&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dgreen_tripdata_2019-10.csv.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
connected. to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443...
HTTP request sent, awaiting response... 200 OK
Length: 8262584 (7,9M) [application/octet-stream]
Saving to: ‘green_tripdata_2019-10.csv.gz.1’

green_tripdata_2019 100%[===================>]   7,88M  5,26MB/s    in 1,5s

2025-01-22 13:21:17 (5,26 MB/s) - ‘green_tripdata_2019-10.csv.gz.1’ saved [8262584/8262584]

In [4]:
import gzip
import shutil

# Input and output file paths
input_file = 'green_tripdata_2019-10.csv.gz'  # Path to .csv.gz file
output_file = 'green_tripdata_2019-10.csv'  # Path to extracted .csv file

# Open the .csv.gz file and decompress it into a .csv
with gzip.open(input_file, 'rt') as gz_file:
    with open(output_file, 'w') as csv_file:
        shutil.copyfileobj(gz_file, csv_file)

print(f"File extracted to: {output_file}")

File extracted to: green_tripdata_2019-10.csv

In [5]:
df = pd.read_csv('green_tripdata_2019-10.csv', nrows=100)

In [6]:
df.sample(5)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
13,2,2019-10-01 00:44:56,2019-10-01 00:51:06,N,5,18,169,1,1.19,10.0,0.0,0.0,0.25,0.0,NaN,0.0,10.25,1,2,0.00
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.5,0.5,0.00,0.0,NaN,0.3,22.80,2,1,0.00
83,1,2019-10-01 00:57:47,2019-10-01 01:00:14,N,1,41,42,4,0.60,4.0,0.5,0.5,3.00,0.0,NaN,0.3,8.30,1,1,0.00
32,2,2019-10-01 00:37:54,2019-10-01 00:50:51,N,1,130,205,1,3.60,13.0,0.5,0.5,0.00,0.0,NaN,0.3,14.30,2,1,0.00
15,2,2019-10-01 00:06:06,2019-10-01 00:11:05,N,1,75,262,1,1.24,6.0,0.5,0.5,2.01,0.0,NaN,0.3,12.06,1,1,2.75

In [7]:
print(df.dtypes)

VendorID                   int64
lpep_pickup_datetime      object
lpep_dropoff_datetime     object
store_and_fwd_flag        object
RatecodeID                 int64
PULocationID               int64
DOLocationID               int64
passenger_count            int64
trip_distance            float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
ehail_fee                float64
improvement_surcharge    float64
total_amount             float64
payment_type               int64
trip_type                  int64
congestion_surcharge     float64
dtype: object

In [8]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [9]:
print(df.dtypes)

VendorID                          int64
lpep_pickup_datetime     datetime64[ns]
lpep_dropoff_datetime    datetime64[ns]
store_and_fwd_flag               object
RatecodeID                        int64
PULocationID                      int64
DOLocationID                      int64
passenger_count                   int64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                      int64
trip_type                         int64
congestion_surcharge            float64
dtype: object

In [10]:
from sqlalchemy import create_engine

In [11]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
engine.connect()

In [51]:
df.head(n=0).to_sql('green_taxi_data', con=engine, if_exists='replace')

0

In [52]:
df_iter = pd.read_csv('green_tripdata_2019-10.csv', iterator=True, chunksize = 100000, low_memory=False)

In [53]:
df = next(df_iter)

In [54]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [55]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1.0,0.00
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1.0,0.00
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1.0,0.00
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1.0,0.00
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2,2019-10-08 15:45:56,2019-10-08 15:54:45,N,1,95,95,1,0.85,7.0,0.00,0.5,0.00,0.0,NaN,0.3,7.80,2,1.0,0.00
99996,2,2019-10-08 15:43:31,2019-10-08 15:50:11,N,1,74,41,1,0.53,6.0,0.00,0.5,0.00,0.0,NaN,0.3,6.80,2,1.0,0.00
99997,2,2019-10-08 15:57:26,2019-10-08 16:17:41,N,1,75,141,1,1.94,13.0,0.00,0.5,2.98,0.0,NaN,0.3,19.53,1,1.0,2.75
99998,2,2019-10-08 14:58:24,2019-10-08 15:03:40,N,1,33,33,1,0.89,6.0,0.00,0.5,1.36,0.0,NaN,0.3,8.16,1,1.0,0.00
99999,2,2019-10-08 15:10:20,2019-10-08 15:17:44,N,1,33,40,1,1.24,7.0,0.00,0.5,0.00,0.0,NaN,0.3,7.80,2,1.0,0.00

In [56]:
df.to_sql(name='green_taxi_data', con=engine, if_exists = 'append')

1000

In [57]:
from time import time

In [58]:
while True:
    try:
        t_start = time()
    
        df = next(df_iter)
    
        df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
        df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
        
        df.to_sql(name='green_taxi_data', con=engine, if_exists='append')
    
        t_end = time()
    
        print('inserted another chunk, took %.3f second' % (t_end - t_start))
    except StopIteration:
            # Break the loop when no more chunks are available
            print("Finished ingesting data into the database.")
            break

inserted another chunk, took 16.122 second
inserted another chunk, took 16.366 second
inserted another chunk, took 16.276 second
inserted another chunk, took 10.743 second
Finished ingesting data into the database.

In [4]:
!wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

--2025-01-22 13:18:06--  https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
Resolving github.com (github.com)... 140.82.114.3
connected. to github.com (github.com)|140.82.114.3|:443...
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250122T121807Z&X-Amz-Expires=300&X-Amz-Signature=378050c2e8083915e900e03c76726a19a9f396703b484077ceecfd6514aed35d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream [following]
--2025-01-22 13:18:07--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/513814948/5a2cc2f5-b4cd-4584-9c62-a6ea97ed0e6a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250122T121807Z&X-Amz-Expires=300&X-Amz-Signature=378050c2e8083915e900e03c76726a19a9f396703b484077ceecfd6514aed35d&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dtaxi_zone_lookup.csv&response-content-type=application%2Foctet-stream
185.199.108.133, 185.199.109.133, 185.199.110.133, ...busercontent.com)...
connected. to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.108.133|:443...
HTTP request sent, awaiting response... 200 OK
Length: 12322 (12K) [application/octet-stream]
Saving to: ‘taxi_zone_lookup.csv’

taxi_zone_lookup.cs 100%[===================>]  12,03K  --.-KB/s    in 0,1s

2025-01-22 13:18:08 (91,8 KB/s) - ‘taxi_zone_lookup.csv’ saved [12322/12322]

In [61]:
df_zones = pd.read_csv('taxi_zone_lookup.csv')

In [62]:
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [63]:
df_zones.to_sql(name='zones', con=engine, if_exists='replace')

265